quarkus.http.port=9000

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=update

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=linuxdistro_store
%dev.quarkus.datasource.devservices.username=store
%dev.quarkus.datasource.devservices.password=store

%prod.quarkus.datasource.username=${DB_USERNAME:store}
%prod.quarkus.datasource.password=${DB_PASSWORD:store}
%prod.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5432/linuxdistro_store}

mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:publicKey.pem}
mp.jwt.verify.issuer=${JWT_ISSUER:https://linuxdistro-roguelite-store.kris.ch/issuer}
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:privateKey.pem}
smallrye.jwt.new-token.issuer=${JWT_ISSUER:https://linuxdistro-roguelite-store.kris.ch/issuer}

# Every JAX-RS endpoint must explicitly declare @PermitAll/@RolesAllowed/@DenyAll, otherwise it's rejected.
quarkus.security.jaxrs.deny-unannotated-endpoints=true
